[package]
name = "rlunaroratings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Api dependencies
nickel = "0.11.0"
serde = { version = "1.0.0", features = ["derive"] }

serde_json = "1.0"
dotenv = "0.15.0"

# Cryptography
sha256 = "1.0.3"