[package]
name = "lunars"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Api dependencies
nickel = "0.11.0"
serde = { version = "1.0.139", features = ["derive"] }
hyper = "0.14.20"

# Common
serde_json = "1.0.82"
dotenv = "0.15.0"
time = "0.3.11"

# Cryptography
sha256 = "1.0.3"

# Database
rusqlite = { version = "0.28.0", features = ["bundled"] }

# QOL Development dependencies
try-catch = "0.2.2"

# Log
log = "0.4.17"
flexi_logger = "0.23.0"