
services:
  lunars:
    build: '.'
    hostname: 'lunars'
    container_name: 'lunars'
    restart: 'unless-stopped'
    ports:
    - '127.0.0.1:58081:58081'
    volumes:
    - ./logs:/usr/src/Lunars/logs
    depends_on:
      db:
        condition: service_started
        restart: true

  db:
    image: mysql:9.1
    restart: unless-stopped
    hostname: 'lunars-db'
    container_name: 'lunars-db'
    environment:
     MYSQL_DATABASE: lunars
     MYSQL_USER: lunars_backend
     MYSQL_PASSWORD: wKzdFWYSWqqNBYseliFdQLuoKGgrxcOh
     MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
    - ./data:/var/lib/mysql
