
services:
  lunars:
    build: '.'
    hostname: 'lunars'
    container_name: 'lunars'
    restart: 'unless-stopped'
    ports:
    - '58081:58081'
    volumes:
    - ./:/home/code/Lunars/
    depends_on:
      db:
        condition: service_started
        restart: true

  db:
    image: mysql
    restart: unless-stopped
    environment:
     MYSQL_DATABASE: lunars
     MYSQL_USER: lunars_backend
     MYSQL_PASSWORD: wKzdFWYSWqqNBYseliFdQLuoKGgrxcOh
     MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
    - ./data:/var/lib/mysql
