version: '3'

services:
  lunars:
    image: 'lunars'
    build: '.'
    hostname: 'lunars'
    container_name: 'lunars'
    restart: 'unless-stopped'
    ports:
    - '6767:6767'
    volumes:
      - ./:/home/code/Lunars/

volumes:
  lunars:
    external: true
